### ISSUE TITLE
Adapter crash at value change for dimmer

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.openhab#4]
When changing value of dimmer adapter crashes:
`
openhab.0	2017-07-02 23:04:43.342	info	connected
openhab.0	2017-07-02 23:04:43.256	info	starting. Version 0.1.3 in /opt/iobroker/node_modules/iobroker.openhab, node: v4.8.3
host.HomeControl	2017-07-02 23:04:42.308	info	instance system.adapter.openhab.0 started with pid 118386
host.HomeControl	2017-07-02 23:04:12.270	info	Restart adapter system.adapter.openhab.0 because enabled
host.HomeControl	2017-07-02 23:04:12.269	error	instance system.adapter.openhab.0 terminated with code 0 (OK)
openhab.0	2017-07-02 23:04:12.246	info	terminating
openhab.0	2017-07-02 23:04:12.221	info	cleaned everything up...
openhab.0	2017-07-02 23:04:12.219	error	at processImmediate [as _immediateCallback] (timers.js:396:17)
openhab.0	2017-07-02 23:04:12.219	error	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.openhab/node_modules/request/request.js:581:7)
openhab.0	2017-07-02 23:04:12.219	error	at end (/opt/iobroker/node_modules/iobroker.openhab/node_modules/request/request.js:552:18)
openhab.0	2017-07-02 23:04:12.219	error	at Request.write (/opt/iobroker/node_modules/iobroker.openhab/node_modules/request/request.js:1514:27)
openhab.0	2017-07-02 23:04:12.219	error	at ClientRequest.OutgoingMessage.write (_http_outgoing.js:459:11)
openhab.0	2017-07-02 23:04:12.219	error	TypeError: first argument must be a string or Buffer
openhab.0	2017-07-02 23:04:12.216	error	uncaught exception: first argument must be a string or Buffer
openhab.0	2017-07-02 23:04:12.190	warn	Cannot write "openhab.0.items.Dimmer_Test": Error: Argument error, options.body.`

**Comment by DutchmanNL** [comment]
solved with 1.0.4, thank you Bluefox !
